apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-app.fullname" . }}-secrets
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ required "secret.dbPassword is required" .Values.secret.dbPassword | quote }}